# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       libofono-qt

# >> macros
# << macros

Summary:    Qt bindings for oFono
Version:    0.53
Release:    1
Group:      System/Libraries
License:    LGPLv2.1
URL:        http://meego.gitorious.org/meego-cellular/ofono-qt
Source0:    %{name}-%{version}.tar.bz2
Source100:  libofono-qt.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(QtCore)
BuildRequires:  pkgconfig(QtDBus)
BuildRequires:  doxygen

%description
This package contains the Qt bindings for a number of oFono cellular service
interfaces.


%package devel
Summary:    Development files for the oFono Qt bindings
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   %{name} = %{version}

%description devel
This package contains the development header files for the oFono Qt bindings.

%package doc
Summary:    Documentation for the oFono Qt bindings
Group:      Documentation
Requires:   %{name} = %{version}-%{release}

%description doc
This package contains the documentation for the oFono Qt bindings.

%package tests
Summary:    Unit and functional tests for the oFono Qt bindings
Group:      Development/Tools
Requires:   %{name} = %{version}-%{release}

%description tests
This package contains the unit and functional tests for the oFono Qt bindings.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# Copy the documentation
cp -a doc/html %{buildroot}%{_datadir}/doc/ofono-qt/
# Fix wrong path in prl files
find %{buildroot}%{_libdir} -type f -name '*.prl' \
-exec sed -i -e "/^QMAKE_PRL_BUILD_DIR/d;s/\(QMAKE_PRL_LIBS =\).*/\1/" {} \;
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%{_libdir}/%{name}.so.*
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_libdir}/%{name}.prl
%{_libdir}/%{name}.so
%{_libdir}/pkgconfig/ofono-qt.pc
%{_includedir}/ofono-qt/%{name}_global.h
%{_includedir}/ofono-qt/ofono*.h
%{_datadir}/qt4/mkspecs/features/ofono-qt.prf
# >> files devel
# << files devel

%files doc
%defattr(-,root,root,-)
%doc %{_datadir}/doc/ofono-qt/
# >> files doc
# << files doc

%files tests
%defattr(-,root,root,-)
/opt/tests/%{name}/test_ofono*
# >> files tests
# << files tests
